version: '3'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile 
    container_name: service1-service   
    networks:
      - my_network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile 
    container_name: service2-service
    ports:
      - "5002:5002"
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - service1
      - service2

networks:
  my_network: